config/routes.rb
Rails.application.routes.draw do
  devise_for :users, sign_out_via: [:get, :post]

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  resources :users, only: [:index, :show] do
    resources :posts, only: [:index, :show, :new, :create, :destroy] do
      resources :comments, only: [:index, :show, :new, :create, :destroy]
      resources :likes, only: [:new, :create]
    end
  end

  # Defines the root path route ("/")
  # root "articles#index"
  root "users#index"
  post 'authenticate', to: 'authentication#authenticate'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the user here. For example:
    #
    #   return unless user.present?
    #   can :read, :all
    #   return unless user.admin?
    #   can :manage, :all
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, published: true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/blob/develop/docs/define_check_abilities.md

    can :read, :all # start by defining rules for all users, also not logged ones
    return unless user.present?

    can :manage, Post, author_id: user.id # if the user is logged in can manage it's own posts
    can :manage, Comment, author_id: user.id # can manage own comments in the website
    can :manage, Like, author_id: user.id # can manage own likes in the website
    can :create, Comment # logged in users can also create comments to any post
    can :create, Like # logged in users can also likes to any post
    return unless user.admin?

    can :manage, :all # finally we give all remaining permissions only to the admins
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :author, class_name: 'User', foreign_key: 'author_id'
  belongs_to :post, foreign_key: 'post_id', class_name: 'Post'
  after_save :increase_comment_counter
  after_destroy :decrease_comment_counter

  def increase_comment_counter
    post.increment!(:comments_counter)
  end

  def decrease_comment_counter
    post.decrement!(:comments_counter)
  end
end
2

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :author, class_name: 'User', foreign_key: 'author_id'
  belongs_to :post
  after_save :increase_likes_counter

  def increase_likes_counter
    post.increment!(:likes_counter)
  end
end

app/models/post.rb
class Post < ApplicationRecord
  validates :title, presence: true, length: { in: 1..250 }
  validates :comments_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :likes_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy

  belongs_to :author, class_name: 'User', foreign_key: 'author_id'
  after_save :update_posts_counter
  after_destroy :decrease_posts_counter
  after_initialize :init

  def return_recent_comments
    comments.order(created_at: :desc).limit(5)
  end

  def decrease_posts_counter
    author.decrement!(:post_counter)
  end

  def init
    self.comments_counter ||= 0
    self.likes_counter ||= 0
  end

  private

  def update_posts_counter
    author.increment!(:post_counter)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
  validates :name, presence: true
  validates :post_counter, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  has_many :posts, dependent: :destroy, foreign_key: 'author_id'
  has_many :likes, dependent: :destroy, foreign_key: 'author_id'
  has_many :comments, dependent: :destroy, foreign_key: 'author_id'

  after_initialize :init

  has_many :posts, foreign_key: 'author_id'
  has_many :comments, foreign_key: 'author_id'
  has_many :likes, foreign_key: 'author_id'

  def recent_posts
    Post.order(created_at: :desc).limit(3)
  end

  def admin?
    role == 'admin'
  end

  private

  def init
    self.post_counter ||= 0
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # def current_user
  #   User.first
  # end
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  before_action :update_allowed_parameters, if: :devise_controller?

  protected

  def update_allowed_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :surname, :email, :password, :bio, :photo) }
    devise_parameter_sanitizer.permit(:account_update) do |u|
      u.permit(:name, :surname, :email, :password, :current_password, :bio, :photo)
    end
  end

  rescue_from CanCan::AccessDenied do |exception|
    redirect_to root_url, alert: exception.message
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  load_and_authorize_resource

  def create
    @comment = Comment.new(comment_params)
    @comment.author = current_user
    @post = Post.find(params[:post_id])
    # @post = Post.includes(:author, comments: [:author]).find(params[:post_id])
    # @post = Post.includes(:author, comments: %i[author post]).find(params[:post_id])

    @comment.post = @post
    if @comment.save
      redirect_to user_posts_path(@post.author_id, @post.id)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def new
    @comment = Comment.new
  end

  def destroy
    @comment = Comment.find(params[:id])
    @post = @comment.post
    @comment.destroy
    redirect_to user_post_path(@post.author, @post)
  end

  def comment_params
    params.require(:comment).permit(:text)
  end

  private

  def set_user
    @user = User.find(params[:user_id])
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  load_and_authorize_resource

  def create
    @like = Like.new
    @post = Post.find(params[:post_id])
    @user = User.find(params[:user_id])
    @like.author = current_user
    @like.post = @post
    if @like.save
      redirect_to user_post_path(@user, @post)
    else
      render :new, status: :unprocessable_entity
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  load_and_authorize_resource

  def index
    @user = User.find(params[:user_id])
    @posts = @user.posts
  end

  def show
    @post = Post.includes(comments: [:author]).find(params[:id])
    @user = User.find(params[:user_id])
  end

  def new
    @post = Post.new
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to user_posts_path(current_user, @post), notice: 'Post deleted successfully'
  end

  def create
    # @post = Post.new(post_params)
    # @post = Post.new(title: post_params[:title], text: post_params[:text], author: current_user)
    # @post.author = current_user
    new_post = current_user.posts.new(post_params)
    new_post.likes_counter = 0
    new_post.comments_counter = 0

    if new_post.save
      redirect_to user_posts_path(current_user)
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def post_params
    params.require(:post).permit(:title, :text)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  load_and_authorize_resource

  def index
    @users = User.all
    @user = current_user
  end

  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/comments/new.html.erb
<h1>Hello</h1>

<%= form_with model: @comment, url: user_post_comments_path do |form| %>
  <div>
    <%= form.label :text %>
    <%= form.text_area :text %>
  </div>
  <%= form.submit "submit"%>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    
    <%= stylesheet_link_tag "users.css" %>
    <%= stylesheet_link_tag "posts.css" %>
    <%= stylesheet_link_tag "login.css" %>
    <%= stylesheet_link_tag "signup.css" %>


  </head>

  <body>

    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    
    <div class='menu'>
      <ul>
        <% if user_signed_in? %>
          <li class="logout">
            <%= link_to "Add User", new_user_registration_path, class: "nav-link" %>
          </li>
          <li class="logout-allign">
            <%= link_to "Sign Out", destroy_user_session_path, data: { turbo_method: :delete, turbo_confirm: "Are you sure?" }, class: "nav-link" %>
          </li>
        <% else %>
          <li class="logout-allign">
            <%= link_to "Sign Up", new_user_registration_path, class: "nav-link" %>
          </li>
          <li class="logout-allign">
            <%= link_to "Sing In", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>

    <%= yield %>
  </body>
</html>

app/views/posts/index.html.erb
<div class='post-main'>
  <h1>List all posts</h1>
  <div class='users-list'>
    <div class='user-img'>
      <img src="<%= @user.photo %>" alt="<%= @user.name %>">
    </div>
    <div class='user-info'>
      <h2><%= @user.name %></h2>
      <h5>Number of posts: <%= @user.posts.count %></h5>
    </div>
  </div>
  <ul>
      <% @posts.each do |post| %>
        <li>
          <h3 class="post-title">Post #<%= post.id %></h3>
          <h3><%= link_to post.title, user_post_path(@user.id, post) %></h3>
          <p><%= post.text %></p>
          <% if can? :destroy, post%>
            <%= form_with url: "/users/#{@user.id}/posts/#{post.id}" , method: :delete do |f|%>
              <%= f.submit 'Delete', class: 'delete-post-btn' %>
            <%end%>
          <%end%>
          <p>Comments <%= post.comments_counter %>, Likes <%= post.likes_counter %></p>
          <ul>
            <% post.return_recent_comments.includes(:author).each do |comment| %>
              <li><%= comment.author.name %> : <%= comment.text%></li>
            <% end %>
          </ul>
        </li>
      <% end %>
  </ul>
    <button>Pagination</button>
</div>

app/views/posts/new.html.erb
<section>
  <h1>Create post</h1>
  <%= form_with model: @post, url: user_posts_path do |form| %>
    <div>
      <%= form.label :title%>
      <%= form.text_field :title %>
    </div>

    <div>
      <%= form.label :text%>
      <%= form.text_area :text %>
    </div>

    <%= form.submit "submit"%>
  <% end %>
</section>

app/views/posts/show.html.erb
<section class='post-sec'>
  <div class='post-info'>
    <h3> <%=@post.title %>  by <%= @post.author.name%></h3>
    <div class='post-react'>
      <h5>Comments: <%= @post.comments_counter%></h5>
      <h5>Likes: <%= @post.likes_counter%></h5>
    </div>
  </div>
  <div class='post-text'><p><%= @post.text%></p></div>
  <div class='comments'>
    <ul>
      <% @post.comments.each do |comment| %>
        <li><%= comment.author.name%> : <%= comment.text%></li>
      <% end %>
    </ul>
  </div>
  <div>
    <%= link_to "comment", new_user_post_comment_path(user_id: @post.author_id, post_id: @post.id )%>
    <%= form_with model: @like, url: user_post_likes_path(post_id: @post.id) do |form| %>
    <%= form.submit "Like"%>
    <% end %>
  </div>
</section>

app/views/users/index.html.erb
<div class='main-div'>
  <h1>
    List of all Users
  </h1>

  

  <ul>

  <% @users.each do |user| %>
    <li>
      <div class='users-list'>
        <div class='user-img'>
          <%# <%= image_tag user.photo %> 
        </div>
        <div class='user-info'>
          <h2><%= link_to user.name, user_path(user) %></h2>
          <h5>Number of posts: <%= user.post_counter %></h5>
        </div>
      </div>
    </li>
  <% end %>
  </ul>
  <%# <%= link_to 'Create post', new_user_post_path(@user) %> %>
</div>

app/views/users/show.html.erb
<div class='user-show'>


  <div class='users-list'>
    <div class='user-img'>
      <img src="<%= @user.photo %>" alt="<%= @user.name %>">
    </div>
    <div class='user-info'>
      <h2><%= @user.name %></h2>
      <h5>Number of posts: <%= @user.posts.count %></h5>
    </div>
  </div>
  <div class='bio'>
    <h3>Bio</h3>
    <p><%= @user.bio %></p>
  </div>


    <div>
      <%= link_to "Add New Post", "/users/#{@user.id}/posts/new" %>
    </div>


    <% @user.posts.each do |post| %>
      <div class='posts'>
        <h3><%= link_to post.title, user_post_path(@user.id, post) %></h3>
        <div class='post-text'>
          <p><%= post.text%></p>
          <div class='post-react'>
            <h5>Comments: <%= post.comments_counter%></h5>
            <h5>Likes: <%= post.likes_counter%></h5>
          </div>
          
        </div>
      </div>
    <% end %>

    <%= link_to "See all posts", user_posts_path(@user) %>

</div>